#!/usr/bin/env bash
# loop-runner.sh — Goal-driven supervisor+worker loop
#
# Architecture:
#   Each iteration:
#     1. Supervisor reads GOAL + codebase state + prior git history
#        → plans tasks in ===TASK=== format, OR outputs STATUS: CONVERGED
#     2. Workers execute all tasks IN PARALLEL via run-tasks-parallel.sh
#     3. Repeat until CONVERGED or max iterations
#
# The programmer provides a GOAL file describing the ideal end state.
# The supervisor does task breakdown and re-plans each iteration.
# Workers are parallel (batch-tasks style).
#
# Usage:
#   bash loop-runner.sh GOAL_FILE [options]
#
#   --model MODEL         supervisor model: haiku|sonnet|opus  (default: sonnet)
#   --worker-model MODEL  worker model (default: same as supervisor)
#   --max-iter N          max iterations (default: 10)
#   --max-workers N       max parallel workers per iteration (default: 4)
#   --state FILE          state file (default: .claude/loop-state)
#   --context FILE        codebase context file (pre-generated by /loop skill)
#   --log-dir DIR         log directory (default: logs/loop)
#   --resume              resume from previous state (default: fresh start)

set -uo pipefail

# Graceful shutdown on SIGTERM/SIGINT
_cleanup() {
  echo ""
  echo "⚠ Loop interrupted (signal). Saving state..."
  [[ -n "${STATE_FILE:-}" ]] && state_write INTERRUPTED true
  [[ -n "${PROGRESS_FILE:-}" ]] && write_progress "interrupted" "signal"
  type _notify_loop &>/dev/null && _notify_loop "interrupted" "✗ Loop interrupted: $(basename ${GOAL_FILE:-unknown}) at iter ${iteration:-?}"
  exit 130
}
trap _cleanup SIGTERM SIGINT

# Allow nested claude calls from within a Claude Code session
unset CLAUDECODE 2>/dev/null || true

GOAL_FILE="${1:?Usage: loop-runner.sh GOAL_FILE [--model MODEL] [--max-iter N]}"
SUPERVISOR_MODEL="sonnet"
WORKER_MODEL=""
MAX_ITER=10
MAX_WORKERS=4
STATE_FILE=".claude/loop-state"
CONTEXT_FILE=""
LOG_DIR="logs/loop"
COST_LOG=".claude/loop-cost.log"
CUMULATIVE_COST=0
RESUME=false
EXIT_GATE=""
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
START_TIME=$(date +%s)

# Source canonical model IDs
source "$SCRIPTS_DIR/../models.env" 2>/dev/null || source "$HOME/.claude/models.env"

shift
while [[ $# -gt 0 ]]; do
  case "$1" in
    --model)         SUPERVISOR_MODEL="$2"; shift 2 ;;
    --worker-model)  WORKER_MODEL="$2";     shift 2 ;;
    --max-iter)      MAX_ITER="$2";         shift 2 ;;
    --max-workers)   MAX_WORKERS="$2";      shift 2 ;;
    --state)         STATE_FILE="$2";       shift 2 ;;
    --context)       CONTEXT_FILE="$2";     shift 2 ;;
    --log-dir)       LOG_DIR="$2";          shift 2 ;;
    --resume)        RESUME=true;           shift ;;
    --exit-gate)     EXIT_GATE="$2";       shift 2 ;;
    *)               echo "Unknown flag: $1" >&2; shift ;;
  esac
done

[[ -z "$WORKER_MODEL" ]] && WORKER_MODEL="$SUPERVISOR_MODEL"

model_id() {
  case "$1" in
    haiku)  echo "$MODEL_HAIKU" ;;
    sonnet) echo "$MODEL_SONNET" ;;
    opus)   echo "$MODEL_OPUS" ;;
    *)      echo "$1" ;;
  esac
}

SUPERVISOR_MODEL_ID=$(model_id "$SUPERVISOR_MODEL")

mkdir -p "$LOG_DIR" "$(dirname "$STATE_FILE")"

# ── Pre-flight: check source vs deployed script mismatch ──────────────────────
DEPLOY_DIR="$HOME/.claude/scripts"
_deploy_mismatch=false
for _script in run-tasks.sh run-tasks-parallel.sh loop-runner.sh; do
  _src="$SCRIPTS_DIR/$_script"
  _dst="$DEPLOY_DIR/$_script"
  if [[ -f "$_src" && -f "$_dst" ]] && ! diff -q "$_src" "$_dst" &>/dev/null; then
    echo "⚠ WARNING: source $_script differs from deployed $_dst"
    _deploy_mismatch=true
  fi
done
if $_deploy_mismatch; then
  echo "  Run install.sh to sync source → ~/.claude/scripts/"
  echo "  Continuing in 5s..."
  sleep 5
fi
unset _deploy_mismatch _script _src _dst

# ── State file (KEY=VALUE) ────────────────────────────────────────────────────
state_read() {
  grep -m1 "^${1}=" "$STATE_FILE" 2>/dev/null | cut -d= -f2- || echo "${2:-}"
}
state_write() {
  local key="$1" val="$2"
  if [[ -f "$STATE_FILE" ]] && grep -q "^${key}=" "$STATE_FILE"; then
    sed -i "s|^${key}=.*|${key}=${val}|" "$STATE_FILE"
  else
    echo "${key}=${val}" >> "$STATE_FILE"
  fi
}

if ! $RESUME || [[ ! -f "$STATE_FILE" ]]; then
  # Fresh start: reset state (default behavior)
  { echo "ITERATION=0"; echo "CONVERGED=false"; echo "GOAL=$(realpath "$GOAL_FILE")"; echo "STARTED=$(date -Iseconds)"; echo "STARTED_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo 'HEAD')"; } > "$STATE_FILE"
fi

iteration=$(state_read ITERATION 0)

# ── Progress file ─────────────────────────────────────────────────────────────
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PROGRESS_FILE="$LOG_DIR/${TIMESTAMP}-progress"

write_progress() {
  cat > "$PROGRESS_FILE" <<EOF
STATUS=$1
ITERATION=$iteration
MAX_ITER=$MAX_ITER
GOAL=$GOAL_FILE
SUPERVISOR=$SUPERVISOR_MODEL
WORKER=$WORKER_MODEL
ACTION=${2:-}
EOF
}

# Auto-write PROGRESS.md entry on convergence
_write_loop_progress() {
  local goal_name started iterations project_dir log_summary progress_file
  goal_name=$(basename "${GOAL_FILE}" .md)
  started=$(state_read STARTED "unknown")
  iterations="${iteration}"
  project_dir="${PROJECT_DIR:-$(pwd)}"
  progress_file="${project_dir}/PROGRESS.md"

  # Get commits since loop started
  log_summary=$(git -C "${project_dir}" log --oneline --since="${started}" 2>/dev/null | head -20 || echo "no commits found")

  if [[ -f "$progress_file" ]]; then
    local entry
    entry="### $(date '+%Y-%m-%d') — Loop: ${goal_name}\n\n**Iterations:** ${iterations}\n**Goal file:** ${GOAL_FILE}\n**Commits since start:**\n\`\`\`\n${log_summary}\n\`\`\`\n\n---\n\n"
    # Prepend entry after the first line (the # Progress Log header)
    local tmp
    tmp=$(mktemp)
    head -3 "$progress_file" > "$tmp"
    printf "%b" "$entry" >> "$tmp"
    tail -n +4 "$progress_file" >> "$tmp"
    mv "$tmp" "$progress_file"
  fi
}

# Notify via Telegram on convergence/interruption
_notify_loop() {
  local status="$1" msg="$2"
  # Try project-local notify script first, then global
  local notify_script=""
  for candidate in "${PROJECT_DIR:-$(pwd)}/configs/hooks/notify-telegram.sh" \
                   "${HOME}/.claude/hooks/notify-telegram.sh"; do
    if [[ -f "$candidate" ]]; then notify_script="$candidate"; break; fi
  done
  [[ -z "$notify_script" ]] && return 0
  [[ -z "${TELEGRAM_TOKEN:-}" ]] && return 0
  bash "$notify_script" "$msg" 2>/dev/null &
}

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo "╔════════════════════════════════════════╗"
echo "║       Claude Code — Goal Loop          ║"
echo "╚════════════════════════════════════════╝"
echo "  Goal:       $GOAL_FILE"
echo "  Supervisor: $SUPERVISOR_MODEL"
echo "  Worker:     $WORKER_MODEL (max $MAX_WORKERS parallel)"
echo "  Max iter:   $MAX_ITER"
echo "  State:      $STATE_FILE"
echo ""

write_progress "running" "init"

EXTRA_CONTEXT=""

# ── Main loop ─────────────────────────────────────────────────────────────────
while [[ $iteration -lt $MAX_ITER ]]; do
  # Check for STOP sentinel (allows /loop --stop from another session)
  if [[ "$(state_read STOP false)" == "true" ]]; then
    write_progress "stopped" "user-requested"
    echo "⚠ STOP sentinel found in state file. Exiting."
    exit 0
  fi

  # Check for Tier 3 blocker (written by worker in previous iteration)
  if [[ -f ".claude/blockers.md" ]]; then
    echo "⚠ Blocker detected (.claude/blockers.md exists). Stopping loop."
    echo "  Review the blocker, resolve it, then delete .claude/blockers.md to continue."
    write_progress "blocked" "tier3-blocker"
    _notify_loop "blocked" "⚠ Tier 3 blocker detected — human input required"
    exit 1
  fi

  iteration=$((iteration + 1))
  ITER_START_TIME=$(date +%s)
  state_write ITERATION "$iteration"

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Iteration $iteration / $MAX_ITER"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  write_progress "running" "supervisor-$iteration"

  # ── Gather codebase state for supervisor ──────────────────────────────────
  [[ -f "$GOAL_FILE" ]] || { echo "Error: goal file missing: $GOAL_FILE" >&2; write_progress "error" "goal-missing"; exit 1; }

  # Parse MODE from first 10 lines of goal file
  LOOP_MODE=$(head -10 "$GOAL_FILE" | grep "^MODE:" | cut -d: -f2 | xargs)
  LOOP_MODE="${LOOP_MODE:-VERTICAL}"

  goal_content=$(cat "$GOAL_FILE")
  git_log=$(git log --oneline -20 2>/dev/null || echo "(no git history)")
  git_status=$(git status --short 2>/dev/null | head -20 || echo "(no git repo)")
  git_recent_diff=$(git diff "$(state_read STARTED_COMMIT HEAD)"..HEAD --stat 2>/dev/null | tail -20 || echo "(no diff)")

  extra_context=""
  if [[ -n "$CONTEXT_FILE" && -f "$CONTEXT_FILE" ]]; then
    extra_context=$(cat "$CONTEXT_FILE")
  fi

  # ── Build supervisor prompt ───────────────────────────────────────────────
  PROMPT_FILE=$(mktemp /tmp/loop-supervisor-XXXXXX.md)
  {
    cat << 'HEADER'
You are a planning+evaluation supervisor for an autonomous improvement loop.

Each iteration you:
  1. Evaluate what has been done so far (via git history)
  2. Compare to the goal — what's still missing?
  3. Plan the next batch of tasks, OR declare convergence

HEADER

    echo "## Goal"
    echo "$goal_content"
    echo ""

    if [[ -n "$extra_context" ]]; then
      echo "## Codebase Context"
      echo "$extra_context"
      echo ""
    fi

    echo "## Current State (Iteration $iteration / $MAX_ITER)"
    echo ""
    echo "### Recent commits (what workers have done so far)"
    echo "$git_log"
    echo ""
    echo "### Working tree status"
    echo "$git_status"
    echo ""
    if [[ $iteration -gt 1 ]]; then
      echo "### Files changed since loop started"
      echo "$git_recent_diff"
      echo ""
    fi

    # Set mode-specific task instructions
    if [[ "$LOOP_MODE" == "HORIZONTAL" ]]; then
      LOOP_MODE_INSTRUCTION="output up to 20 file-level micro-tasks. Each task MUST touch exactly 1 file. Use model: haiku for all tasks."
      MAX_TASKS_RULE="- Max 20 tasks per iteration (HORIZONTAL mode: one file per task)"
    else
      LOOP_MODE_INSTRUCTION="output 1–4 tasks"
      MAX_TASKS_RULE="- Max 4 tasks per iteration"
    fi

    if [[ -n "$EXTRA_CONTEXT" ]]; then
      echo "## Exit Gate Feedback"
      echo -e "$EXTRA_CONTEXT"
      echo ""
    fi

    cat << INSTRUCTIONS
## Your task

Compare the goal against what has been implemented (read the recent commits and diffs above).

If the goal is FULLY achieved, output exactly:
  STATUS: CONVERGED

Otherwise, ${LOOP_MODE_INSTRUCTION} in this EXACT format (no preamble, no explanation):

===TASK===
model: haiku|sonnet|opus
timeout: 600
retries: 1
---
{Task description: 3–8 sentences. Be specific:
 - Which file to edit and which function/section
 - What exactly to implement
 - How to verify it works
 - Commit with: committer "type: msg" file1 file2}

===TASK===
model: sonnet
...

Rules:
- Each task must be INDEPENDENT (workers run in parallel; no task may depend on another's output)
${MAX_TASKS_RULE}
- Workers commit via: committer "type: message" file1 file2  (NEVER git add .)
- Workers have full Claude Code tool access (Read, Edit, Bash, Glob, Grep)
- Pick model by complexity: haiku=mechanical/1-file, sonnet=standard, opus=architectural/multi-file
- Do NOT re-assign tasks that are already in the git log as completed commits

## 3-Tier Issue Handling (for workers)

Each task description MUST include these rules for the worker:

**Tier 1 — Uncertainty (pick a default, keep going):**
When you're unsure about a minor choice (naming, ordering, style), pick the reversible default.
Log: append a timestamped entry to \`.claude/decisions.md\`:
\`\`\`
## [ISO-timestamp] Decision: [what you decided]
Context: [why you were unsure]
Choice: [what you picked and why]
\`\`\`
Then continue working. Do NOT stop for minor ambiguities.

**Tier 2 — Task failure (skip, log, continue):**
If your task fails after reasonable attempts (compile error you can't fix, missing dependency, test won't pass):
Log: append a timestamped entry to \`.claude/skipped.md\`:
\`\`\`
## [ISO-timestamp] Skipped: [task summary]
Reason: [what failed]
Attempted: [what you tried]
\`\`\`
Commit any partial work, then stop this task. Do NOT loop retrying.

**Tier 3 — True blocker (stop everything):**
Only for: destructive/irreversible operations, needs secrets/permissions you don't have, mutually exclusive directions with high rollback cost.
Write to \`.claude/blockers.md\`:
\`\`\`
## [ISO-timestamp] Blocker: [what's blocking]
Impact: [what can't proceed]
Needs: [what human input is required]
\`\`\`
Then stop immediately. Do NOT attempt workarounds for true blockers.

## Blocker detection (for supervisor)

If \`.claude/blockers.md\` appears in the recent git diff (was written during this loop run), output:
  STATUS: CONVERGED
A Tier 3 blocker requires human input before proceeding.

## Drift prevention

If you discover a new approach or direction change during work:
- Write it to BRAINSTORM.md with \`[AI]\` prefix
- Never modify GOALS.md or VISION.md directly — those are human-owned anchor files
- Continue with the current task plan; the new idea will be reviewed later
INSTRUCTIONS
    EXTRA_CONTEXT=""
  } > "$PROMPT_FILE"

  # ── Run supervisor ────────────────────────────────────────────────────────
  SUPERVISOR_LOG="$LOG_DIR/iter-${iteration}-supervisor.log"
  echo "  Supervisor planning ($SUPERVISOR_MODEL)..."

  SUPERVISOR_JSON=$(
    timeout 300s claude -p \
      --model "$SUPERVISOR_MODEL_ID" \
      --dangerously-skip-permissions \
      --output-format json \
      < "$PROMPT_FILE" \
      2>"$SUPERVISOR_LOG" \
    || echo '{"result":"ERROR: supervisor failed — see '"$SUPERVISOR_LOG"'","total_cost_usd":0}'
  )
  rm -f "$PROMPT_FILE"

  # Extract text result and cost from JSON
  SUPERVISOR_OUTPUT=$(echo "$SUPERVISOR_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('result',''))" 2>/dev/null || echo "$SUPERVISOR_JSON")
  ITER_SUPERVISOR_COST=$(echo "$SUPERVISOR_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('total_cost_usd',0))" 2>/dev/null || echo 0)

  echo ""
  echo "  Supervisor output:"
  echo "$SUPERVISOR_OUTPUT" | sed 's/^/  │ /'
  echo "  Supervisor cost: \$${ITER_SUPERVISOR_COST}"
  echo ""

  # ── Check convergence ────────────────────────────────────────────────────
  if echo "$SUPERVISOR_OUTPUT" | grep -q "STATUS: CONVERGED"; then
    if [[ -n "$EXIT_GATE" ]]; then
      echo "  Running exit gate: ${EXIT_GATE}"
      if eval "$EXIT_GATE" > /tmp/loop-gate-output 2>&1; then
        echo "  ✓ Exit gate passed"
        state_write CONVERGED true
        write_progress "converged" ""
        ( _write_loop_progress ) &
        _notify_loop "converged" "✓ Loop converged: $(basename $GOAL_FILE) in ${iteration} iterations"
        echo "✓ Goal achieved — loop converged at iteration $iteration"
        break
      else
        echo "  ✗ Exit gate failed — continuing loop with failure context"
        EXTRA_CONTEXT="Exit gate failed:\n$(cat /tmp/loop-gate-output | tail -20)\nDo NOT output STATUS: CONVERGED until the exit gate passes."
      fi
    else
      state_write CONVERGED true
      write_progress "converged" ""
      ( _write_loop_progress ) &
      _notify_loop "converged" "✓ Loop converged: $(basename $GOAL_FILE) in ${iteration} iterations"
      echo "✓ Goal achieved — loop converged at iteration $iteration"
      break
    fi
  fi

  if echo "$SUPERVISOR_OUTPUT" | grep -qi "^ERROR:"; then
    write_progress "error" "supervisor-failed"
    echo "⚠ Supervisor failed. Stopping." >&2; exit 1
  fi

  # ── Build task file ───────────────────────────────────────────────────────
  ITER_TASKS="$LOG_DIR/iter-${iteration}-tasks.txt"

  if echo "$SUPERVISOR_OUTPUT" | grep -q "^===TASK===$"; then
    # Supervisor output proper format — use directly, append self-review footer to each task
    PROCESSED=$(mktemp /tmp/loop-tasks-XXXXXX.txt)
    in_body=false
    seen_first_task=false
    while IFS= read -r line; do
      if [[ "$line" == "===TASK===" ]]; then
        if $in_body; then
          # End of previous task body — append self-review
          echo ""
          echo "## Commit & self-review"
          echo "- Use committer \"type: msg\" file1 file2 to commit (NEVER git add .)"
          echo "- Re-read every changed file before finishing"
          echo "- Run compile / type-check if applicable"
          echo "- Do NOT modify the goal file — the supervisor tracks completion via git log"
        fi
        echo "===TASK==="
        in_body=false
        seen_first_task=true
      elif [[ "$line" == "---" ]] && ! $in_body && $seen_first_task; then
        echo "---"
        in_body=true
      elif $seen_first_task; then
        echo "$line"
      fi
      # Lines before first ===TASK=== are preamble — skip them
    done <<< "$SUPERVISOR_OUTPUT" >> "$PROCESSED"
    # Append footer to last task
    if $in_body; then
      {
        echo ""
        echo "## Commit & self-review"
        echo "- Use committer \"type: msg\" file1 file2 to commit (NEVER git add .)"
        echo "- Re-read every changed file before finishing"
        echo "- Run compile / type-check if applicable"
      } >> "$PROCESSED"
    fi
    mv "$PROCESSED" "$ITER_TASKS"
  else
    # Supervisor didn't use ===TASK=== format — wrap entire output as one task
    {
      echo "===TASK==="
      echo "model: $WORKER_MODEL"
      echo "timeout: 1800"
      echo "retries: 1"
      echo "---"
      echo "$SUPERVISOR_OUTPUT"
      echo ""
      echo "## Commit & self-review"
      echo "- Use committer \"type: msg\" file1 file2 to commit (NEVER git add .)"
      echo "- Re-read every changed file before finishing"
      echo "- Run compile / type-check if applicable"
      echo "- Mark the completed item in the goal file: change \`- [ ]\` to \`- [x]\`"
    } > "$ITER_TASKS"
  fi

  # Show task summary
  task_count=$(grep -c "^===TASK===$" "$ITER_TASKS" || echo 0)
  echo "  Planned $task_count task(s) for this iteration"
  echo ""

  # ── Run workers in parallel ───────────────────────────────────────────────
  write_progress "running" "workers-$iteration"
  ITER_START_SHA=$(git rev-parse HEAD 2>/dev/null || echo "")
  COST_MARKER=$(mktemp /tmp/loop-cost-marker-XXXXXX)
  echo "  Running $task_count worker(s) in parallel (MAX_WORKERS=$MAX_WORKERS)..."
  MAX_WORKERS="$MAX_WORKERS" bash "$SCRIPTS_DIR/run-tasks-parallel.sh" "$ITER_TASKS" 2>&1

  # Check if workers produced any commits (Bug 3: non-code task silent failure)
  if [[ -n "$ITER_START_SHA" ]]; then
    ITER_COMMIT_COUNT=$(git rev-list "$ITER_START_SHA"..HEAD --count 2>/dev/null || echo 0)
    if [[ "$ITER_COMMIT_COUNT" -eq 0 ]]; then
      echo "  ⚠ Workers produced 0 commits this iteration."
      EXTRA_CONTEXT="Workers produced no commits in the previous iteration. If this is expected (documentation/research task with no code changes), you may declare CONVERGED. If unexpected, treat as Tier 2 failure and re-plan with different approach."
    else
      echo "  ✓ $ITER_COMMIT_COUNT commit(s) this iteration."
    fi
  fi

  # ── Log iteration cost ──────────────────────────────────────────────────
  # Worker logs live in logs/claude-tasks/ (created by run-tasks-parallel.sh).
  # Find logs newer than the marker file created before workers started.
  ITER_WORKER_COST=0
  WORKER_LOG_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)/logs/claude-tasks"
  for wlog in $(find "$WORKER_LOG_DIR" -name "*.log" -newer "$COST_MARKER" 2>/dev/null); do
    [[ -f "$wlog" ]] || continue
    wcost=$(grep -o '"total_cost_usd":[0-9.]*' "$wlog" 2>/dev/null | tail -1 | cut -d: -f2 || echo 0)
    ITER_WORKER_COST=$(python3 -c "print(round($ITER_WORKER_COST + ${wcost:-0}, 4))" 2>/dev/null || echo "$ITER_WORKER_COST")
  done
  rm -f "$COST_MARKER"
  ITER_TOTAL_COST=$(python3 -c "print(round(${ITER_SUPERVISOR_COST:-0} + $ITER_WORKER_COST, 4))" 2>/dev/null || echo 0)
  CUMULATIVE_COST=$(python3 -c "print(round(${CUMULATIVE_COST:-0} + $ITER_TOTAL_COST, 4))" 2>/dev/null || echo "$ITER_TOTAL_COST")
  ITER_DURATION=$(( ($(date +%s) - ITER_START_TIME) / 60 ))
  ELAPSED=$(( ($(date +%s) - START_TIME) / 60 ))

  mkdir -p "$(dirname "${COST_LOG:-.claude/loop-cost.log}")"
  echo "ITER=$iteration COST=\$$ITER_TOTAL_COST CUMULATIVE=\$$CUMULATIVE_COST SUPERVISOR=\$$ITER_SUPERVISOR_COST WORKERS=\$$ITER_WORKER_COST DURATION=${ITER_DURATION}min ELAPSED=${ELAPSED}min TASKS=$task_count" >> "${COST_LOG:-.claude/loop-cost.log}"
  echo "  Cost: \$$ITER_TOTAL_COST this iter (cumulative: \$$CUMULATIVE_COST) | ${ITER_DURATION}min | ${ELAPSED}min elapsed"

  echo ""
  echo "  Iteration $iteration complete."
done

# ── Final ─────────────────────────────────────────────────────────────────────
if [[ "$(state_read CONVERGED false)" != "true" ]]; then
  write_progress "max-iter" ""
  echo ""
  echo "⚠ Reached max iterations ($MAX_ITER). Goal may be partially achieved."
  echo "  Check git log for what was done. Run again to continue."
fi

TOTAL_ELAPSED=$(( ($(date +%s) - START_TIME) / 60 ))
echo ""
echo "Logs:     $LOG_DIR/"
echo "State:    $STATE_FILE"
echo "Progress: $PROGRESS_FILE"
echo "Cost:     \$$CUMULATIVE_COST over ${TOTAL_ELAPSED}min ($iteration iterations)"
echo "Cost log: $COST_LOG"

# ── Auto-deploy: run install.sh if configs/ was modified ──────────────────────
INSTALL_SH="${PROJECT_DIR:-$(pwd)}/install.sh"
if [[ -f "$INSTALL_SH" ]]; then
  CONFIGS_CHANGED=$(git -C "${PROJECT_DIR:-$(pwd)}" diff --name-only "$(state_read STARTED_COMMIT HEAD)"..HEAD 2>/dev/null | grep "^configs/" | wc -l | tr -d ' \n' || echo 0)
  if [[ "${CONFIGS_CHANGED:-0}" -gt 0 ]]; then
    echo ""
    echo "⚙ configs/ changed — running install.sh to deploy..."
    bash "$INSTALL_SH" 2>&1 | grep -E "^(Installed|  Installed|Installation complete)" || true
    echo "✓ Deployed to ~/.claude/"
  fi
fi
