#!/usr/bin/env bash
# provider-switch.sh — Switch the active LLM provider for Claude Code
#
# Usage: provider-switch.sh [provider-name]
#        provider-switch.sh          → show current provider
#        provider-switch.sh minimax  → switch to minimax
#        provider-switch.sh claude   → switch to claude (default)
#
# Writes ~/.claude/.provider-env.sh with the correct ANTHROPIC_BASE_URL
# and ANTHROPIC_API_KEY export. ~/.zshrc should source that file.

set -euo pipefail

PROVIDERS_FILE="$HOME/.claude/providers.json"
ENV_FILE="$HOME/.claude/.provider-env.sh"

# ─── Bootstrap providers.json if missing ────────────────────────────

if [[ ! -f "$PROVIDERS_FILE" ]]; then
  cat > "$PROVIDERS_FILE" << 'PROVIDERS_EOF'
{
  "active": "claude",
  "providers": {
    "claude": {
      "name": "Anthropic Claude",
      "base_url": null,
      "api_key_env": "ANTHROPIC_API_KEY_CLAUDE",
      "models": ["claude-sonnet-4-6", "claude-opus-4-6", "claude-haiku-4-5-20251001"],
      "note": "Set ANTHROPIC_API_KEY_CLAUDE in ~/.zshrc (or leave unset to use existing ANTHROPIC_API_KEY)"
    },
    "minimax": {
      "name": "Minimax",
      "base_url": "https://api.minimax.chat/v1",
      "api_key_env": "MINIMAX_CODING_API_KEY",
      "models": ["MiniMax-Text-01", "abab6.5s-chat"],
      "note": "Set MINIMAX_CODING_API_KEY in ~/.zshrc"
    }
  }
}
PROVIDERS_EOF
  echo "Created $PROVIDERS_FILE"
fi

# ─── Parse args ──────────────────────────────────────────────────────

TARGET="${1:-}"

# Show status if no arg
if [[ -z "$TARGET" ]]; then
  ACTIVE=$(jq -r '.active' "$PROVIDERS_FILE")
  echo "Active provider: $ACTIVE"
  echo ""
  echo "Available providers:"
  jq -r '.providers | to_entries[] | "  \(.key): \(.value.name) — models: \(.value.models | join(", "))"' "$PROVIDERS_FILE"
  echo ""
  if [[ -f "$ENV_FILE" ]]; then
    echo "Current env ($ENV_FILE):"
    cat "$ENV_FILE"
  else
    echo "No env file yet. Run: provider-switch.sh <provider>"
  fi
  exit 0
fi

# Validate provider exists
if ! jq -e --arg p "$TARGET" '.providers[$p]' "$PROVIDERS_FILE" > /dev/null 2>&1; then
  echo "ERROR: Unknown provider '$TARGET'"
  echo "Available: $(jq -r '.providers | keys | join(", ")' "$PROVIDERS_FILE")"
  exit 1
fi

# ─── Switch provider ─────────────────────────────────────────────────

PROVIDER_NAME=$(jq -r --arg p "$TARGET" '.providers[$p].name' "$PROVIDERS_FILE")
BASE_URL=$(jq -r --arg p "$TARGET" '.providers[$p].base_url // "null"' "$PROVIDERS_FILE")
API_KEY_ENV=$(jq -r --arg p "$TARGET" '.providers[$p].api_key_env' "$PROVIDERS_FILE")
MODELS=$(jq -r --arg p "$TARGET" '.providers[$p].models | join(", ")' "$PROVIDERS_FILE")

# Write env file
{
  echo "# Auto-generated by provider-switch.sh — do not edit manually"
  echo "# Provider: $PROVIDER_NAME"
  echo "# Switch with: provider-switch.sh <provider>"
  echo ""
  if [[ "$BASE_URL" == "null" ]]; then
    echo "unset ANTHROPIC_BASE_URL 2>/dev/null || true"
  else
    echo "export ANTHROPIC_BASE_URL=\"$BASE_URL\""
  fi
  echo "export ANTHROPIC_API_KEY=\"\${${API_KEY_ENV}:-\${ANTHROPIC_API_KEY:-}}\""
} > "$ENV_FILE"

# Update active in providers.json
TMP=$(mktemp)
jq --arg p "$TARGET" '.active = $p' "$PROVIDERS_FILE" > "$TMP" && mv "$TMP" "$PROVIDERS_FILE"

echo "Switched to: $PROVIDER_NAME"
echo "Models: $MODELS"
echo ""
echo "Written: $ENV_FILE"
echo ""
echo "To apply: restart Claude Code (env vars take effect at startup)"
echo "One-time: source $ENV_FILE && claude"
