#!/usr/bin/env bash
# Claude Code compatibility adapter for a user-maintained providers.json.
# The universal Clade source of truth is a secret-free connection identity;
# this script intentionally knows nothing about current vendors or model IDs.

set -euo pipefail

providers_file="${CLADE_CLAUDE_PROVIDERS_FILE:-${HOME}/.claude/providers.json}"
env_file="${CLADE_CLAUDE_PROVIDER_ENV_FILE:-${HOME}/.claude/.provider-env.sh}"
target="${1:-}"

if ! command -v jq >/dev/null 2>&1; then
  echo "provider-switch: jq is required" >&2
  exit 2
fi
if [[ ! -f "$providers_file" ]]; then
  echo "provider-switch: no trusted user provider registry at $providers_file" >&2
  echo "Create it explicitly; Clade will not bootstrap stale endpoints, models, or credentials." >&2
  exit 2
fi
if ! jq -e '
  type == "object"
  and (.providers | type == "object")
  and all(.providers[];
    type == "object"
    and (.runtime // "claude") == "claude"
    and (.name | type == "string")
    and (.models | type == "array")
    and all(.models[]; type == "string")
    and ((.base_url // null) == null or (.base_url | type == "string"))
    and ((.api_key_env // null) == null or (.api_key_env | type == "string"))
  )
' "$providers_file" >/dev/null; then
  echo "provider-switch: invalid registry schema" >&2
  exit 2
fi

if [[ -z "$target" ]]; then
  active="$(jq -r '.active // "unknown"' "$providers_file")"
  echo "Active Claude connection: $active"
  jq -r '
    .providers | to_entries[] |
    "  \(.key): \(.value.name) — models: \(.value.models | join(", "))"
  ' "$providers_file"
  exit 0
fi

if ! jq -e --arg id "$target" '.providers[$id] != null' "$providers_file" >/dev/null; then
  echo "provider-switch: unknown connection '$target'" >&2
  echo "Available: $(jq -r '.providers | keys | join(", ")' "$providers_file")" >&2
  exit 2
fi

base_url="$(jq -r --arg id "$target" '.providers[$id].base_url // ""' "$providers_file")"
api_key_env="$(jq -r --arg id "$target" '.providers[$id].api_key_env // ""' "$providers_file")"
primary_model="$(jq -r --arg id "$target" '.providers[$id].models[0] // ""' "$providers_file")"
provider_name="$(jq -r --arg id "$target" '.providers[$id].name' "$providers_file")"

if [[ -z "$primary_model" ]]; then
  echo "provider-switch: connection '$target' has no model" >&2
  exit 2
fi
case "$primary_model" in
  *[!A-Za-z0-9._:/+-]*)
    echo "provider-switch: model is not a valid opaque identifier" >&2
    exit 2
    ;;
esac
if [[ -n "$api_key_env" && ! "$api_key_env" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "provider-switch: api_key_env must be an environment variable name" >&2
  exit 2
fi

env_dir="$(dirname "$env_file")"
mkdir -p "$env_dir"
tmp_env="$(mktemp "${env_dir}/.provider-env.XXXXXX")"
tmp_registry="$(mktemp "$(dirname "$providers_file")/.providers.XXXXXX")"
trap 'rm -f "$tmp_env" "$tmp_registry"' EXIT
chmod 600 "$tmp_env"
{
  echo "# Generated by provider-switch.sh for connection: $target"
  if [[ -n "$base_url" ]]; then
    printf 'export ANTHROPIC_BASE_URL=%q\n' "$base_url"
  else
    echo "unset ANTHROPIC_BASE_URL 2>/dev/null || true"
  fi
  if [[ -n "$api_key_env" ]]; then
    printf 'if [[ -n "${%s:-}" ]]; then export ANTHROPIC_API_KEY="${%s}"; else unset ANTHROPIC_API_KEY 2>/dev/null || true; fi\n' "$api_key_env" "$api_key_env"
  else
    echo "unset ANTHROPIC_API_KEY 2>/dev/null || true"
  fi
  printf 'export ANTHROPIC_MODEL=%q\n' "$primary_model"
} > "$tmp_env"
mv "$tmp_env" "$env_file"

jq --arg id "$target" '.active = $id' "$providers_file" > "$tmp_registry"
chmod --reference="$providers_file" "$tmp_registry" 2>/dev/null || chmod 600 "$tmp_registry"
mv "$tmp_registry" "$providers_file"

echo "Selected Claude connection: $target ($provider_name)"
echo "Model: $primary_model"
echo "Start a new Claude Code session, or source: $env_file"
