#!/usr/bin/env bash
# provider-switch.sh — Switch the active LLM provider for Claude Code
#
# Usage: provider-switch.sh [provider-name]
#        provider-switch.sh          → show current provider
#        provider-switch.sh minimax  → switch to minimax
#        provider-switch.sh claude   → switch to claude (default)
#
# Writes ~/.claude/.provider-env.sh with ANTHROPIC_BASE_URL and optionally
# ANTHROPIC_API_KEY (only when a provider key is set — Max subscription uses
# claude login without API key). ~/.zshrc should source that file.

set -euo pipefail

PROVIDERS_FILE="$HOME/.claude/providers.json"
ENV_FILE="$HOME/.claude/.provider-env.sh"

# ─── Bootstrap providers.json if missing ────────────────────────────

if [[ ! -f "$PROVIDERS_FILE" ]]; then
  cat > "$PROVIDERS_FILE" << 'PROVIDERS_EOF'
{
  "active": "claude",
  "providers": {
    "claude": {
      "name": "Anthropic Claude",
      "base_url": null,
      "api_key_env": "ANTHROPIC_API_KEY_CLAUDE",
      "models": ["claude-sonnet-4-6", "claude-opus-4-6", "claude-haiku-4-5-20251001"],
      "note": "Max subscription: leave unset; use claude login. Optional API key: set ANTHROPIC_API_KEY_CLAUDE in ~/.zshrc"
    },
    "minimax": {
      "name": "Minimax",
      "base_url": "https://api.minimax.chat/v1",
      "api_key_env": "MINIMAX_CODING_API_KEY",
      "models": ["MiniMax-Text-01", "abab6.5s-chat"],
      "note": "Set MINIMAX_CODING_API_KEY in ~/.zshrc"
    }
  }
}
PROVIDERS_EOF
  echo "Created $PROVIDERS_FILE"
fi

# ─── Parse args ──────────────────────────────────────────────────────

TARGET="${1:-}"

# Show status if no arg
if [[ -z "$TARGET" ]]; then
  ACTIVE=$(jq -r '.active' "$PROVIDERS_FILE")
  echo "Active provider: $ACTIVE"
  echo ""
  echo "Available providers:"
  jq -r '.providers | to_entries[] | "  \(.key): \(.value.name) — models: \(.value.models | join(", "))"' "$PROVIDERS_FILE"
  echo ""
  if [[ -f "$ENV_FILE" ]]; then
    echo "Current env ($ENV_FILE):"
    cat "$ENV_FILE"
  else
    echo "No env file yet. Run: provider-switch.sh <provider>"
  fi
  exit 0
fi

# Validate provider exists
if ! jq -e --arg p "$TARGET" '.providers[$p]' "$PROVIDERS_FILE" > /dev/null 2>&1; then
  echo "ERROR: Unknown provider '$TARGET'"
  echo "Available: $(jq -r '.providers | keys | join(", ")' "$PROVIDERS_FILE")"
  exit 1
fi

# ─── Switch provider ─────────────────────────────────────────────────

PROVIDER_NAME=$(jq -r --arg p "$TARGET" '.providers[$p].name' "$PROVIDERS_FILE")
BASE_URL=$(jq -r --arg p "$TARGET" '.providers[$p].base_url // "null"' "$PROVIDERS_FILE")
API_KEY_ENV=$(jq -r --arg p "$TARGET" '.providers[$p].api_key_env // "ANTHROPIC_API_KEY_CLAUDE"' "$PROVIDERS_FILE")
MODELS=$(jq -r --arg p "$TARGET" '.providers[$p].models | join(", ")' "$PROVIDERS_FILE")
PRIMARY_MODEL=$(jq -r --arg p "$TARGET" '.providers[$p].models[0]' "$PROVIDERS_FILE")

# Write env file
# For Anthropic (no proxy): do not export empty ANTHROPIC_API_KEY — that breaks
# Max subscription auth (`claude login`). Only export when a key env is set.
{
  echo "# Auto-generated by provider-switch.sh — do not edit manually"
  echo "# Provider: $PROVIDER_NAME"
  echo "# Switch with: provider-switch.sh <provider>"
  echo ""
  if [[ "$BASE_URL" == "null" ]]; then
    echo "unset ANTHROPIC_BASE_URL 2>/dev/null || true"
  else
    echo "export ANTHROPIC_BASE_URL=\"$BASE_URL\""
  fi
  echo "_key=\"\${${API_KEY_ENV}:-\${ANTHROPIC_API_KEY:-}}\""
  echo "if [[ -n \"\$_key\" ]]; then"
  echo "  export ANTHROPIC_API_KEY=\"\$_key\""
  echo "else"
  echo "  unset ANTHROPIC_API_KEY 2>/dev/null || true"
  echo "fi"
  echo "unset _key"
} > "$ENV_FILE"

# Update active in providers.json
TMP=$(mktemp)
jq --arg p "$TARGET" '.active = $p' "$PROVIDERS_FILE" > "$TMP" && mv "$TMP" "$PROVIDERS_FILE"

# Also update model in settings.json so Claude Code picks it up
SETTINGS_FILE="$HOME/.claude/settings.json"
if [[ -f "$SETTINGS_FILE" ]]; then
  TMP2=$(mktemp)
  jq --arg m "$PRIMARY_MODEL" '.model = $m' "$SETTINGS_FILE" > "$TMP2" && mv "$TMP2" "$SETTINGS_FILE"
fi

echo "Switched to: $PROVIDER_NAME"
echo "Models: $MODELS"
echo ""
echo "Written: $ENV_FILE"
echo "Updated: $SETTINGS_FILE (model → $PRIMARY_MODEL)"
echo ""
echo "Restart Claude Code to apply — or run:"
echo "  source $ENV_FILE && claude"
