#!/usr/bin/env python3
"""Generate the orchestrator settings reference from _SETTINGS_DEFAULTS.

`docs/configuration.md` tells the reader that
`~/.claude/orchestrator-settings.example.json` holds "a reference copy of every
supported orchestrator key" and that install.sh "overwrites [it] on every run
so it always matches the current `_SETTINGS_DEFAULTS`". `install.sh` does
overwrite it — with a hand-maintained template that tracks nothing. Measured on
2026-08-29, minutes after a fresh `./install.sh`:

    _SETTINGS_DEFAULTS   75 keys
    the template         33 keys   (43 missing, 1 stale)

The stale one is worse than the missing ones: `worker_provider` is no longer a
setting, so a reader copying it out of the "reference" sets a key nothing ever
reads. Among the missing were three security controls added the same week —
`worker_structured_output`, `worker_require_worktree`, `worker_git_surface_guard`.

Generating the file makes the documented promise true, and `--check` in CI
keeps it true. Key ORDER follows `_SETTINGS_DEFAULTS` source order, which is
already grouped by concern, so the reference stays readable rather than
alphabetised into noise.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ORCHESTRATOR = REPO_ROOT / "orchestrator"
TEMPLATE = REPO_ROOT / "templates" / "orchestrator-settings.example.json"

HEADER_KEY = "_comment"
HEADER = (
    "Example orchestrator settings — copy to ~/.claude/orchestrator-settings.json. "
    "Only override the keys you care about; defaults live in "
    "orchestrator/config.py:_SETTINGS_DEFAULTS, which also carries the comment "
    "explaining each one. GENERATED by configs/scripts/regen-settings-example.py — "
    "edit _SETTINGS_DEFAULTS instead. Never commit this file with real secrets."
)


def settings_defaults() -> dict:
    sys.path.insert(0, str(ORCHESTRATOR))
    import config  # type: ignore[import-not-found]  # noqa: E402 — path set above

    return dict(config._SETTINGS_DEFAULTS)


def expected() -> dict:
    return {HEADER_KEY: HEADER, **settings_defaults()}


def generate() -> None:
    TEMPLATE.write_text(
        json.dumps(expected(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def check() -> int:
    want = expected()
    try:
        have = json.loads(TEMPLATE.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"check-settings-example: cannot read {TEMPLATE}: {exc}", file=sys.stderr)
        return 1

    want_keys = [k for k in want if k != HEADER_KEY]
    have_keys = [k for k in have if k != HEADER_KEY]
    problems: list[str] = []

    for key in want_keys:
        if key not in have:
            problems.append(f"  missing: {key}")
        elif have[key] != want[key]:
            problems.append(f"  {key}: have={have[key]!r} want={want[key]!r}")
    for key in have_keys:
        if key not in want:
            problems.append(f"  stale (no longer a setting): {key}")
    if have.get(HEADER_KEY) != HEADER:
        problems.append("  _comment header drifted")

    if not problems:
        print(f"regen-settings-example: {len(want_keys)} settings documented ✓")
        return 0

    print(
        f"{TEMPLATE} drifted from _SETTINGS_DEFAULTS; "
        "run configs/scripts/regen-settings-example.py",
        file=sys.stderr,
    )
    for line in problems[:40]:
        print(line, file=sys.stderr)
    if len(problems) > 40:
        print(f"  … and {len(problems) - 40} more", file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    generate()
    print(f"Synced {TEMPLATE} ({len(settings_defaults())} settings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
