#!/usr/bin/env python3
"""regen-skill-overrides.py — derive configs/settings-skill-overrides.json from the skills tree.

Why this file exists
--------------------
Claude Code sends the model a listing of every installed skill — one line per
skill, `- name: description - when_to_use` — inside a CHARACTER BUDGET of
`context window × bytes-per-token × skillListingBudgetFraction` (default 1%).
Measured on 2026-09-20 with Claude Code 2.1.258: a 200k-context model gets
8,000 characters, Clade's 144 skills alone are 59,332, and the ~20 bundled
skills that always keep their description take about 8,000 of it first. Over
budget, Claude Code keeps descriptions in order of a per-skill USAGE score
(`usageCount × 0.5^(days/7)`) and lists the rest by name only — so a skill
nobody has invoked yet has score 0, is listed without its description, and
cannot be auto-selected: exactly the skills that are new.

Two levers are official settings (read from the binary's own settings schema,
`skillOverrides` and `skillListingBudgetFraction`) and this file sets both:

- every sub-skill of a hub family (blog-*, seo-*, ads-*) becomes
  `"name-only"`: still listed, still callable through the Skill tool by its hub
  (`/blog write` routes to `blog-write`), but costing `name + 2` characters
  instead of hundreds. `disable-model-invocation` was measured to be the wrong
  knob — the Skill tool refuses such a skill, which breaks hub routing.
- `skillListingBudgetFraction` is raised to the value check-skill-listing.py
  proves sufficient for the whole model-facing listing on a 200k model.

install.sh merges this file into ~/.claude/settings.json with the USER'S own
entries winning, so a per-machine `/skills` decision survives reinstall.

Generated, gated: CI and the pre-commit hook run `--check`; edit the RULES here
and regenerate rather than hand-editing the JSON.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SKILLS = REPO / "configs" / "skills"
OUTPUT = REPO / "configs" / "settings-skill-overrides.json"

# A hub is the skill the family's triggers route through. Its sub-skills are
# reached by the hub or by an explicit /name, never by their own description.
HUB_FAMILIES = ("blog", "seo", "ads", "email")
# Sub-skills that must keep a description anyway (none today; the hubs carry
# the family triggers). Add a name here with the reason in the commit body.
EXEMPT: frozenset[str] = frozenset()

# check-skill-listing.py measured the model-facing listing at 33,950 chars
# against a 200k-window budget of 800,000 × fraction (2026-09-20, 143 skills,
# 81 name-only, after the description trims and the email hub): minimum
# fraction 0.0424, so 0.05 (40,000 chars, about 10k tokens of CAP — what is
# actually sent is the listing itself, ~8.5k tokens) leaves ~6,000 chars of
# headroom, roughly 15 more skills before the gate asks for a trim. Change
# only with a new measurement in the same commit.
BUDGET_FRACTION = 0.05


def name_only_skills(skills_dir: Path = SKILLS) -> list[str]:
    names: list[str] = []
    for d in sorted(skills_dir.iterdir()):
        if not (d / "SKILL.md").is_file():
            continue
        family = d.name.split("-", 1)[0]
        if family in HUB_FAMILIES and d.name != family and d.name not in EXEMPT:
            names.append(d.name)
    return names


def render(skills_dir: Path = SKILLS) -> str:
    payload = {
        "_comment": (
            "GENERATED by configs/scripts/regen-skill-overrides.py — do not hand-edit. "
            "Merged into ~/.claude/settings.json by install.sh; your own skillOverrides "
            "and skillListingBudgetFraction win over these."
        ),
        "skillListingBudgetFraction": BUDGET_FRACTION,
        "skillOverrides": {name: "name-only" for name in name_only_skills(skills_dir)},
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file differs from a fresh render")
    args = parser.parse_args(argv)
    fresh = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != fresh:
            print(f"{OUTPUT.relative_to(REPO)} is out of date; run "
                  f"python3 configs/scripts/regen-skill-overrides.py", file=sys.stderr)
            return 1
        n = len(json.loads(fresh)["skillOverrides"])
        print(f"regen-skill-overrides: up to date ({n} name-only sub-skills, "
              f"fraction {BUDGET_FRACTION})")
        return 0
    OUTPUT.write_text(fresh, encoding="utf-8")
    n = len(json.loads(fresh)["skillOverrides"])
    print(f"wrote {OUTPUT.relative_to(REPO)}: {n} name-only sub-skills, fraction {BUDGET_FRACTION}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
