#!/usr/bin/env bash
# The ONE definition of "has configs/ changed since the last install.sh".
#
# It exists because there were three definitions and they could never agree.
# install.sh wrote .kit-checksum over configs/ excluding __pycache__/*.pyc/*.pyo;
# session-context.sh and start.sh recomputed it with a bare `find -type f`. Any
# tree that has ever run a Python script under configs/ carries gitignored
# bytecode — 105 files on aries — so the two formulas differed by construction,
# the STALE KIT banner was permanently true, and `./install.sh` could not clear
# it. Worse, start.sh turned the same condition into `exit 1` on a non-tty run,
# so unattended starts aborted on a signal no action could satisfy.
#
# A staleness detector that fires on a clean tree is the same defect class this
# repository keeps finding in its own instruments: it reports "changed" whether
# or not anything changed, so the banner carries no information either way.
#
# Sourced by install.sh (the writer) and by session-context.sh and start.sh
# (the readers). Change the expression here and all three move together.
#
# Callers define _SHA256 themselves (sha256sum on Linux, shasum -a 256 on BSD);
# this honours it if set and falls back, so it works standalone under `bash -n`
# and under a hook that sourced it before its own detection ran.

kit_checksum() {
  local dir="$1"
  local -a sha
  if [[ ${#_SHA256[@]} -gt 0 ]]; then
    sha=("${_SHA256[@]}")
  elif command -v sha256sum >/dev/null 2>&1; then
    sha=(sha256sum)
  else
    sha=(shasum -a 256)
  fi
  [[ -d "$dir" ]] || return 1
  # Generated bytecode is not source. It is gitignored, it appears the moment
  # anything under configs/ is imported, and including it makes the checksum a
  # function of whether a script happened to run rather than of what is in the
  # tree.
  find "$dir" -type f \
    ! -path '*/__pycache__/*' ! -name '*.pyc' ! -name '*.pyo' \
    | LC_ALL=C sort | xargs "${sha[@]}" 2>/dev/null \
    | "${sha[@]}" | cut -d' ' -f1
}

kit_checksum_self_test() {
  local tmp rc=0 a b
  tmp=$(mktemp -d) || return 1
  mkdir -p "$tmp/configs/pkg/__pycache__"
  printf 'x\n' > "$tmp/configs/pkg/real.py"
  a=$(kit_checksum "$tmp/configs")
  # POSITIVE control: bytecode appearing must NOT move the checksum.
  printf 'compiled\n' > "$tmp/configs/pkg/__pycache__/real.cpython-312.pyc"
  printf 'compiled\n' > "$tmp/configs/pkg/real.pyc"
  b=$(kit_checksum "$tmp/configs")
  if [[ "$a" != "$b" ]]; then
    echo "SELF-TEST FAILED: generated bytecode moved the kit checksum ($a -> $b)"
    rc=1
  fi
  # NEGATIVE control: a real source change MUST move it.
  printf 'y\n' > "$tmp/configs/pkg/real.py"
  b=$(kit_checksum "$tmp/configs")
  if [[ "$a" == "$b" ]]; then
    echo "SELF-TEST FAILED: editing a source file did not move the kit checksum"
    rc=1
  fi
  rm -rf "$tmp"
  [[ $rc -eq 0 ]] && echo "SELF-TEST PASSED: bytecode is ignored, a source edit is not"
  return $rc
}

if [[ "${BASH_SOURCE[0]}" == "${0}" && "${1:-}" == "--self-test" ]]; then
  kit_checksum_self_test
fi
